import 'dart:convert';
import 'dart:io';
import 'dart:math';

class GenerateJson {
  // Metodo que convierte un mapa en un archivo json y lo guarda en la carpeta test_data
  static generateJson({required int jsonSize, required String jsonName}) {
    final List<Map<String, dynamic>> list = <Map<String, dynamic>>[];

    for (var i = 0; i < jsonSize; i++) {
      final int randomInt = Random().nextInt(2);
      final String womenOrMan = randomInt != 0 ? 'men' : 'women';

      list.add(<String, dynamic>{
        'userName': randomInt != 0 ? FakeNames.maleName[Random().nextInt(FakeNames.maleName.length)] : FakeNames.femaleName[Random().nextInt(FakeNames.femaleName.length)],
        'userEmail': 'example@gmail.com',
        'sharedTasks': Random().nextInt(30),
        'avatarUrl': 'https://randomuser.me/api/portraits/$womenOrMan/$i.jpg',
        'isShared': Random().nextInt(2) != 0 ? true : false,
        'isOpen': false,
      });
    }

    //Le damos fromato al json
    final String json = JsonEncoder.withIndent('  ').convert(list);
    // Creamos el archivo json en la carpeta actual
    File file = File('lib/$jsonName.json');
    // Crea el archivo json en la ruta especificada
    file.create(recursive: true).then((File file) {
      file.writeAsString(json);
      print('Archivo json generado');
    });
  }
}

class FakeNames {
  // Genera una lista de 500 nombres y apellidos aleatorios en ingles de hombres
  static List<String> maleName = [
    'John Smith',
    'James Johnson',
    'Robert Williams',
    'Michael Brown',
    'William Jones',
    'David Miller',
    'Richard Davis',
    'Charles Garcia',
    'Joseph Rodriguez',
    'Thomas Wilson',
    'Christopher Martinez',
    'Daniel Anderson',
    'Paul Taylor',
    'Mark Thomas',
    'Donald Hernandez',
    'George Lopez',
    'Kenneth Moore',
    'Steven Jackson',
    'Edward Martin',
    'Brian Lee',
    'Ronald King',
    'Anthony Hill',
    'Kevin Walker',
    'Jason White',
    'Matthew Lopez',
    'Gary Clark',
    'Timothy Allen',
    'Jose Rodriguez',
    'Larry Edwards',
    'Jeffrey Torres',
    'Frank Hernandez',
    'Scott Palmer',
    'Eric Nelson',
    'Stephen Hill',
    'Andrew Young',
    'Raymond Lee',
    'Gregory Hall',
    'Joshua Allen',
    'Jerry Lewis',
    'Dennis Wright',
    'Walter Martinez',
    'Patrick Anderson',
    'Peter Thompson',
    'Harold Garcia',
    'Douglas Martinez',
    'Henry Lee',
    'Carl Hall',
    'Arthur Anderson',
    'Ryan Taylor',
    'Roger Moore',
    'Joe Thomas',
    'Juan Hernandez',
    'Jack Martinez',
    'Albert Lopez',
    'Jonathan Thompson',
    'Justin Garcia',
    'Terry Martinez',
    'Gerald Lee',
    'Keith Hall',
    'Samuel Anderson',
    'Willie Taylor',
    'Ralph Moore',
    'Lawrence Thomas',
    'Nicholas Hernandez',
    'Roy Martinez',
    'Benjamin Lopez',
    'Bruce Thompson',
    'Brandon Garcia',
    'Adam Martinez',
    'Harry Lee',
    'Fred Hall',
    'Wayne Anderson',
    'Billy Taylor',
    'Steve Moore',
    'Louis Thomas',
    'Jeremy Hernandez',
    'Aaron Martinez',
    'Randy Lopez',
    'Howard Thompson',
    'Eugene Garcia',
    'Carlos Martinez',
    'Russell Lee',
    'Bobby Hall',
    'Victor Anderson',
    'Martin Taylor',
    'Ernest Moore',
    'Phillip Thomas',
    'Todd Hernandez',
    'Jesse Martinez',
    'Craig Lopez',
    'Alan Thompson',
    'Shawn Garcia',
    'Clarence Martinez',
    'Sean Lee',
  ];

  // Genera una lista de 500 nombres y apellidos aleatorios en ingles de mujeres
  static List<String> femaleName = [
    'Mary Johnson',
    'Patricia Williams',
    'Linda Brown',
    'Barbara Jones',
    'Elizabeth Miller',
    'Jennifer Davis',
    'Maria Garcia',
    'Susan Rodriguez',
    'Margaret Wilson',
    'Dorothy Martinez',
    'Lisa Anderson',
    'Nancy Taylor',
    'Karen Thomas',
    'Betty Hernandez',
    'Helen Lopez',
    'Sandra Moore',
    'Donna Jackson',
    'Carol Martin',
    'Ruth Lee',
    'Sharon King',
    'Michelle Hill',
    'Laura Walker',
    'Sarah White',
    'Kimberly Lopez',
    'Deborah Clark',
    'Jessica Allen',
    'Shirley Rodriguez',
    'Cynthia Edwards',
    'Angela Torres',
    'Melissa Hernandez',
    'Brenda Palmer',
    'Amy Nelson',
    'Anna Hill',
    'Rebecca Young',
    'Virginia Lee',
    'Kathleen Hall',
    'Pamela Allen',
    'Martha Lewis',
    'Debra Wright',
    'Amanda Martinez',
    'Stephanie Anderson',
    'Carolyn Thompson',
    'Christine Garcia',
    'Marie Martinez',
    'Janet Lee',
    'Catherine Hall',
    'Frances Anderson',
    'Ann Taylor',
    'Joyce Moore',
    'Diane Thomas',
    'Alice Hernandez',
    'Julie Martinez',
    'Heather Lopez',
    'Teresa Thompson',
    'Doris Garcia',
    'Gloria Martinez',
    'Evelyn Lee',
    'Jean Hall',
    'Cheryl Anderson',
    'Mildred Taylor',
    'Katherine Moore',
    'Joan Thomas',
    'Ashley Hernandez',
    'Judith Martinez',
    'Rose Lopez',
    'Janet Thompson',
    'Grace Garcia',
    'Judy Martinez',
    'Beverly Lee',
    'Denise Hall',
    'Marilyn Anderson',
    'Amber Taylor',
    'Danielle Moore',
    'Brittany Thomas',
    'Madison Hernandez',
    'Diana Martinez',
    'Jane Lopez',
    'Lori Thompson',
    'Tiffany Garcia',
    'Natalie Martinez',
    'Sara Lee',
    'Abigail Hall',
    'Alexis Anderson',
  ];
}
